version: '3'

services:
  postgres:
    container_name: phone_interpreting_postgres
    restart: unless-stopped
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: phone_interpreter_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379

  core:
    container_name: phone_interpreting_core
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    build:
      context: ../../
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - DOMAIN
      - NODE_ENV=production
      - FALLBACK_PHONE_NUMBER
      - TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN
      - DATABASE_URL
      - REDIS_URL
      - PORT
      - IS_LOCAL
      - CI_ENVIRONMENT_NAME
