
update_staging:
  stage: update_staging
  image: forasoft/dind
  environment: ${CI_COMMIT_REF_NAME}
  tags:
    - hpi-deploy
  script:
    - docker-compose --compatibility -p hpi_${CI_COMMIT_REF_NAME} -f deploy/staging/docker-compose.yml up -d --force-recreate --build
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^(develop)$/ && $CI_PIPELINE_SOURCE == 'push'
      when: always
    - if: $CI_COMMIT_REF_NAME =~ /^(testing|demo)$/ && $CI_PIPELINE_SOURCE == 'push'
      when: manual


